In [1]:
# importa as bibliotecas 
import pandas as pd #biblioteca para a anlise dos dados 
import  plotly.express as px

In [2]:
#importando o arquivo 
vendas = pd.read_excel('analise-vendas.xlsx')
display(vendas)

,Nome do Produto,Preço do Produto,Número da Parcela,Data de Venda,Nome,Email,DDD,Telefone,Tipo de Pagamento,Unnamed: 9
0,Micro-ondas Bratemp,787,12,2022-04-01,Sebastião Martins,sebastiao@gmail.com,64,984200000,Cartão de Credito,NaN
1,Micro-ondas Bratemp,787,12,2022-04-01,Jhonatan Martins,jhonatan@gmail.com,48,991600000,Cartão de Credito,NaN
2,Micro-ondas Bratemp,787,12,2022-04-01,Almir Martins,almir@yahoo.com.br,21,965500000,Cartão de Credito,NaN
3,Micro-ondas Bratemp,787,12,2022-04-01,Antonio Martins,antonio@gmail.com,47,991000000,Cartão de Credito,NaN
4,Micro-ondas Bratemp,787,1,2022-04-01,Gabriel Martins,gabriel@hotmail.com,12,991100000,Boleto Bancário,NaN
...,...,...,...,...,...,...,...,...,...,...
7081,Micro-ondas Philco,599,12,2031-03-31,Mikaelle Martins,mikaelle@gmail.com,11,953900000,Cartão de Credito,NaN
7082,Micro-ondas Philco,599,8,2031-04-01,Rodrigues Martins,rodrigues@gmail.com,84,981200000,Cartão de Credito,NaN
7083,Micro-ondas Philco,599,12,2031-04-02,Silviane Martins,silviane@hotmail.com,91,982200000,Cartão de Credito,NaN
7084,Micro-ondas Philco,599,4,2031-04-03,Karla Martins,karla@outlook.com,79,991200000,Cartão de Credito,NaN
7085,Micro-ondas Bratemp,787,2,2023-01-14,Adriana Martins,adriana@gmail.com,11,992700000,Cartão de Credito,NaN

In [3]:
#vizualizar quantidade de produtos vendidos 
print(vendas['Nome do Produto'].value_counts())

Nome do Produto
Micro-ondas Bratemp      3016
Micro-ondas Panasonic    2021
Micro-ondas Midea        1351
Micro-ondas Eletrolux     286
Micro-ondas Philco        277
Micro-ondas Consul        135
Name: count, dtype: int64

In [4]:
print(vendas['Preço do Produto'].value_counts())

Preço do Produto
787    3016
499    2021
479    1351
549     286
599     277
567     135
Name: count, dtype: int64

In [5]:
print(vendas['DDD'].value_counts())

DDD
11    1576
21     893
31     485
19     269
61     217
      ...
28       8
95       7
46       4
89       3
97       1
Name: count, Length: 67, dtype: int64

qual produto mais vendido? micro-ondas brastemp com 3016 vendas 

qual produto menos vendido? micro-ondas consul com 135 vendas 
ranking dos produtos produtos 
Micro-ondas Bratemp 3016, 
Micro-ondas Panasonic 2021,
Micro-ondas Midea 1351, 
Micro-ondas Eletrolux 286, 
Micro-ondas Philco 277, 
Micro-ondas Consul 135.

qual total vendido de cada produto?
Micro-ondas Bratemp 2.373.592
Micro-ondas Panasonic 1.008.479
Micro-ondas Midea 647.129
Micro-ondas Eletrolux 157.014
Micro-ondas Philco 165.923
Micro-ondas Consul 76.545

qual a região por DDD que mais vendeu?
são paulo com DDD 11, vendeu 1576

In [6]:
#lucro por produto 
print(vendas['Número da Parcela'].value_counts())

Número da Parcela
12    2800
1     2272
10     431
6      350
4      314
3      264
5      217
2      214
7       90
8       76
9       41
11      17
Name: count, dtype: int64

In [7]:
print(vendas['Tipo de Pagamento'].value_counts())

Tipo de Pagamento
Cartão de Credito    6052
Boleto Bancário      1034
Name: count, dtype: int64

nesse projeto analisarei os numeros de vendas de uma loja de electro domesticos em cima de 6 produtos da categoria microodas sendo eles, philco, brasten, consul, eletrolux, panasonic, midea 
essa tabela possui 6 colunas com, nome do produto, preco do produto, numero de parcelas, data de venda, nome do cliente, email do cliente, ddd do cliente, e telefone, tipo de pagamento, valor da comissão

quem quer esta anlise?
qual o produto mais vendido? 
qual a principal forma de pagamento?
se no credito em quantas parcelas sao divididas em ordem crecente?
lucro por produto?

o problema
voce trabalha com analise de dados em um site de vendas, seu chefe quer que voce analise uma categoria de produtos expecifico a de micro-ondas afim de saber qual marca(produto) vendeu mais, qual a forma de pagamento, e de onde sao as pessoas que mais compram, pra fazer possiveis promocoes com os menos vendidos, 

logica 
exporta os bancos de dados 
- pandas, matplotly

exporta o aquivo
- visualizar em busca de erros 
- corrigir os erros 
- 
analise primaria 
- vizualizar quantidade de produtos vendidos 
- lucro por produto 
- formas de pagamento 
- quantidade de pacelas 

analise de grafico 
- exporta todos os graficos 
- formatar os graficos pra melhor visualizaçao

conclusao do problema e a soluçao